# -*- coding: utf-8 -*-
"""Untitled13.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gemkUXYL3mDULQ2gSUIR2JItwnVyRAAu
"""

import streamlit as st
import os
import time
import random
from google import genai
from google.genai.types import GenerateContentConfig, Tool, GoogleSearch
from google.genai.errors import APIError, ServerError
from streamlit.errors import StreamlitAPIException

# ===========================
# 1. CONFIGURATION & SETUP
# ===========================

st.set_page_config(page_title="Financial IQ: Agentic BFSI Analyst", page_icon="📈", layout="wide")

st.markdown("""
<style>
    .badge {
        display: inline-block;
        padding: 0.25em 0.6em;
        font-size: 0.85em;
        font-weight: 700;
        line-height: 1;
        text-align: center;
        white-space: nowrap;
        vertical-align: baseline;
        border-radius: 0.25rem;
        margin-right: 5px;
        margin-bottom: 5px;
    }
    .report-box { border: 1px solid #ddd; padding: 20px; border-radius: 10px; background-color: #f9f9f9; }
</style>
""", unsafe_allow_html=True)

# --- SESSION STATE INITIALIZATION ---
if "research_data" not in st.session_state: st.session_state.research_data = None
if "general_report" not in st.session_state: st.session_state.general_report = None
if "messages" not in st.session_state: st.session_state.messages = []
if "product_name" not in st.session_state: st.session_state.product_name = ""

# --- SIDEBAR CONFIGURATION ---
with st.sidebar:
    st.header("⚙️ Settings")

    # 1. API Key Input
    api_key = None
    try:
        if "GEMINI_API_KEY" in st.secrets:
            api_key = st.secrets["GEMINI_API_KEY"]
    except StreamlitAPIException:
        # st.secrets not available, proceed to check environment or user input
        pass

    if not api_key:
        if "GEMINI_API_KEY" in os.environ:
            api_key = os.environ["GEMINI_API_KEY"]
        else:
            with st.expander("How to get a Key?"):
                st.markdown("[Get Free Key](https://aistudio.google.com/)")
            user_key = st.text_input("Gemini API Key", type="password")
            if user_key:
                api_key = user_key.strip()
                os.environ["GEMINI_API_KEY"] = api_key

    # 2. Model Switcher (3-Way Choice)
    st.divider()
    st.markdown("**🤖 AI Engine**")
    model_choice = st.radio(
        "Select Model:",
        ("Flash 2.0 (Fastest)", "Pro 2.5 (Stable)", "Pro 3.0 (Preview)"),
        index=1, # Default to 2.5 Pro for best reliability/smartness balance
        help="Pro 2.5 is recommended for stable reasoning."
    )

    if model_choice == "Flash 2.0 (Fastest)":
        MODEL_ID = "gemini-2.0-flash-exp"
    elif model_choice == "Pro 2.5 (Stable)":
        MODEL_ID = "gemini-2.5-pro"
    else:
        MODEL_ID = "gemini-2.5-pro"

    if not api_key:
        st.warning("⚠️ Please provide your Gemini API Key to proceed. You can enter it above or set it as an environment variable (GEMINI_API_KEY).")